name: if-else-demo

on:
  workflow_dispatch:
   inputs:
     choose_number:
       description: "Choose any numbers"
       required: true

jobs:
  job:
    runs-on: ubuntu-latest
    steps:
      - name: Tell you your number greater on less than 100
        run: |
          NUMBER=${{ inputs.choose_number }}
          
          if [ $NUMBER -gt 100 ]; then
            echo "$NUMBER number is greater than 100"
          else
            echo "$NUMBER number is less than 100"
            
          

       
    
