name: if-else-demo

on:
  workflow_dispatch:
    inputs:
      choose_number:
        description: "Choose any number"
        required: true

jobs:
  job:
    runs-on: ubuntu-latest
    steps:
      - name: Tell if number is greater or less than 100
        run: |
          NUMBER=${{ inputs.choose_number }}

          if [ "$NUMBER" -gt 100 ]; then
            echo "$NUMBER is greater than 100"
          else
            echo "$NUMBER is less than or equal to 100"
          fi
