name: loops

on:
  workflow_dispatch:

env:
  RUNNER_HOME: "/home/runner/work/gcp-actions/gcp-actions/.github/workflows/"
  

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Run commands
        run: |
          ls -lrth
          pwd
          cd $RUNNER_HOME
          
          echo "Runner home is $RUNNER_HOME"

      - name: Looping files
        run: |
          cd $RUNNER_HOME
          for file in *.yml;
          do
            echo "file found: $file"
          done

  deploy:
   runs-on: ubuntu-latest
   steps:
     - name: "this is second stage"
       run: |
         ls -lrth
         pwd
         COUNT=90
         while [ $COUNT -le 100 ];
         do
           echo "Count is $count"
           count=$((count + 1))
         done

         
         
   
  
