name: loops

on:
  workflow_dispatch:

env:
  RUNNER_HOME: "/home/runner/work/gcp-actions/gcp-actions/.github/workflows/"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Run commands
        run: |
          ls -lrth
          pwd
          cd $RUNNER_HOME
          ls -lrth
          echo "Runner home is $RUNNER_HOME"
